### PR TITLE
Neovim

### PR DESCRIPTION
**Pull request by t-yuki**
Work for neovim.
Note that vim-go support is required.
https://github.com/t-yuki/vim-go/tree/nvim-coverage
https://github.com/fatih/vim-go/pull/686

### CODE REVIEW

**Comment by svanharmelen** [comment]
@t-yuki seems this is work in progress right? As I get this error when using the latest neovim and vim-go:

```
vim-go: testing ...
Error detected while processing /Users/svanharmelen/.config/nvim/plugged/vim-go/autoload/go/jobcontrol.vim:
line  135:
E127: Cannot redefine function <SNR>112_on_exit: It is in use
line  141:
E127: Cannot redefine function <SNR>112_on_stdout: It is in use
line  147:
E127: Cannot redefine function <SNR>112_on_stderr: It is in use
Error detected while processing function go#coverlay#Coverlay:
line   12:
E117: Unknown function: go#jobcontrol#AddHandler
E15: Invalid expression: go#jobcontrol#AddHandler(function('s:coverlay_handler'))
``` 

Also this line misses `call` so it doesn't work as expected: https://github.com/t-yuki/vim-go-coverlay/pull/3/files#diff-8aafe56138bad952b09098b0db501a86R11

**Comment by t-yuki** [comment]
Yes, it is wip because it needs a patch for vim-go https://github.com/fatih/vim-go/pull/686

**Comment by t-yuki** [comment]
However, master branch should work for neovim without async job support.

**Comment by svanharmelen** [comment]
@t-yuki ah, clear then I will not try to use the `neovim` branch for now :grinning: 

So I will use master instead and indeed that one doesn't give me any errors... But it also doesn't give me an overlay :disappointed: Any way I can trouble shoot this?

**Comment by svanharmelen** [comment]
So do I need to turn of or tweak anything manually, or should it just work? As I fail to get it to work and have no clue how to troubleshoot...

Any pointers would be very much appreciated!

**Comment by t-yuki** [comment]
Hmm, It works without tweaks.
Can you run :GoCoverage with SUCCESS which is original vim-go coverage feature?
If it prints error or no output, you may have config error of vim-go.
If it prints SUCCESS, could you run :GoCoverlay ?
If it shows overlay, you may have key mapping error.
Otherwise...??
This repository contains intergrated testing so it may be helpful for deep inspection.

**Comment by t-yuki** [comment]
Also, here is my vimrc. https://github.com/t-yuki/vimfiles/blob/master/_vimrc

**Comment by svanharmelen** [comment]
That is really strange :disappointed: If I try it with this very minimal config, I still don't get any overlays:

```
call plug#begin('~/.config/nvim/plugged')

" Add plugins
Plug 'fatih/vim-go'
Plug 't-yuki/vim-go-coverlay'

call plug#end()

" Set custom key bindings
let mapleader = ' '
let g:mapleader = ' '
let g:go_term_enabled = 1
```

I also tried with `let g:go_term_enabled = 0` as this setting effects if `GoTest` is run async or in a new terminal window. But with either option it still doesn't work... When running the command in debug mode I get the feeling it is not waiting for the async `GoTest` command to finish and so there is no output to use for the overlay.

Did you also test with the latest vim-go an neovim (0.1.2)? As I really think we need a tweak to amke it work for that setup...

**Comment by svanharmelen** [comment]
Ok, so with adding some debug info I was able to determine the problem... The job (`GoTest`) is running async, but `vim-go-coverlay` doesn't expect that and calls `go#coverlay#overlay(l:tmpname)` before the file is actually created...

Will look if there is an easy fix for polling the running job till it's finished or something.

**Comment by t-yuki** [comment]
I'm using ` neovim 0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1`

```
NVIM 0.1.2-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/build/config -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/src -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/.deps/usr/include -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-oVFJ3E/neovim-0.1.1ubuntu1+git201601150803+2156+16~ubuntu15.04.1/build/include
```

**Comment by svanharmelen** [comment]
And for you it works with `neovim`? Are you using the latest (master) from `vim-go` as well?

If I add a `sleep 5` before calling the `overlay` func, it works. But that feels really nasty and if you have a bigger project it will still fail if it needs more then 5 seconds to run all tests.

I don't see an easy way to check if the async job is done a `s:jobs` is not accessible from outside `vim-go`. 

Additionally I noticed that it will only overlay the split that was active when calling `GoCoverlay`. Is it also possible to overlay all the active buffers/splits at once?

**Comment by t-yuki** [comment]
Yes, it works with `neovim`.
I'm using vim-go https://github.com/t-yuki/vim-go/commit/24baa4e9
I've not suffered such synchronous problem.

Well, it sets overlays all buffers at once already. But `coverlay` annotations are only visible after you have moved to another split buffer.

Here is a chart:

image

I didn't realize this behavior and look for the way to show it immediately.

**Comment by t-yuki** [comment]
Opps, @svanharmelen said you use `master@vim-go-coverlay` with `master@vim-go` and `nvim` but this combination not works because `vim-go` always run tests as async but no way to catch complete as you said.
I've misinterpreted your configuration.

I've tested with:

1. `neovim@vim-go-coverlay` with `nvim-coverage@vim-go` and `nvim`
2. `neovim@vim-go-coverlay` with `nvim-coverage@vim-go` and `vim`
3. `master@vim-go-coverlay` with `master@vim-go` and `vim`
4. `master@vim-go-coverlay` with `master@vim-go` and `nvim`

and 4. is not working.

**Comment by svanharmelen** [comment]
Very nice! Will test this tomorrow!

**Pull request merged**
